package com.gokulahealth.ui

import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Bundle
import android.os.Environment
import android.widget.Button
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.gokulahealth.R
import com.gokulahealth.data.AppDatabase
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class HealthPassportActivity : AppCompatActivity() {
    private var cattleId: Int = 1
    private var cattleName: String = "Cow"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_health_passport)

        cattleId   = intent.getIntExtra("cattle_id", 1)
        cattleName = intent.getStringExtra("cattle_name") ?: "Cow"
        title      = "📋 Health Passport"

        val tvPassportInfo = findViewById<TextView>(R.id.tvPassportInfo)
        val db = AppDatabase.getDatabase(this)

        db.cattleDao().getCattleById(cattleId).observe(this) { cattle ->
            cattle?.let {
                tvPassportInfo.text = """
                    🐄 GOKULA-HEALTH PASSPORT
                    ════════════════════════
                    
                    Name         : ${it.name}
                    Ear Tag ID   : ${it.earTagId}
                    Breed        : ${it.breed}
                    Date of Birth: ${it.dateOfBirth}
                    Registered   : ${it.registeredDate}
                    
                    ════════════════════════
                    Generated by Gokula-Health App
                """.trimIndent()
            }
        }

        findViewById<Button>(R.id.btnGeneratePDF).setOnClickListener {
            generateHealthPassportPDF()
        }
    }

    private fun generateHealthPassportPDF() {
        val db = AppDatabase.getDatabase(this)

        db.cattleDao().getCattleById(cattleId).observe(this) { cattle ->
            cattle?.let {
                try {
                    val pdfDocument = PdfDocument()
                    val pageInfo    = PdfDocument.PageInfo.Builder(595, 842, 1).create()
                    val page        = pdfDocument.startPage(pageInfo)
                    val canvas      = page.canvas

                    val titlePaint = Paint().apply {
                        textSize = 22f
                        isFakeBoldText = true
                    }
                    val textPaint = Paint().apply { textSize = 14f }
                    val linePaint = Paint().apply { strokeWidth = 1f }

                    var y = 60f

                    canvas.drawText("GOKULA-HEALTH PASSPORT", 50f, y, titlePaint); y += 10f
                    canvas.drawLine(50f, y, 545f, y, linePaint); y += 30f

                    canvas.drawText("CATTLE INFORMATION", 50f, y, titlePaint); y += 25f
                    canvas.drawText("Name         : ${it.name}", 50f, y, textPaint); y += 20f
                    canvas.drawText("Ear Tag ID   : ${it.earTagId}", 50f, y, textPaint); y += 20f
                    canvas.drawText("Breed        : ${it.breed}", 50f, y, textPaint); y += 20f
                    canvas.drawText("Date of Birth: ${it.dateOfBirth}", 50f, y, textPaint); y += 20f
                    canvas.drawText("Registered   : ${it.registeredDate}", 50f, y, textPaint); y += 30f

                    canvas.drawLine(50f, y, 545f, y, linePaint); y += 20f

                    val today = SimpleDateFormat(
                        "dd/MM/yyyy HH:mm", Locale.getDefault()).format(Date())
                    canvas.drawText("Generated on : $today", 50f, y, textPaint); y += 20f
                    canvas.drawText("Generated by : Gokula-Health App", 50f, y, textPaint)

                    pdfDocument.finishPage(page)

                    val fileName = "${it.name}_HealthPassport.pdf"
                    val file = File(
                        getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),
                        fileName
                    )

                    pdfDocument.writeTo(FileOutputStream(file))
                    pdfDocument.close()

                    Toast.makeText(this,
                        "✅ PDF saved: $fileName",
                        Toast.LENGTH_LONG).show()

                } catch (e: Exception) {
                    Toast.makeText(this,
                        "❌ Error: ${e.message}",
                        Toast.LENGTH_LONG).show()
                }
            }
        }
    }
}